version: "3.9"

services:
  erudismo_app:
    container_name: erudismo_app
    image: erudismo_app_img:1.0.0
    build: .
    ports:
      - "4000:4000"
    environment:
      - DB_URL=postgresql://postgres:postgres@erudismo_db:5432/erudismo_db
    depends_on:
      - erudismo_db
  erudismo_db:
    container_name: erudismo_db
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=erudismo_db
    volumes:
      - ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql